# Lobby spawn
teleport-location:
  world: world
  x: 0.0
  y: 70.0
  z: 0.0
  pitch: 0.0
  yaw: 0.0

# World settings
player-can-break: false # Player without nautiluslobby.break permission cannot break blocks
player-can-place: false # Player without nautiluslobby.place permission cannot place blocks
player-can-heal: false # Player without nautiluslobby.heal permission cannot heal
player-drop-item: false # Player without nautiluslobby.drop permission cannot break drop
player-interact: false # Player without nautiluslobby.interact permission cannot interact with doors, chest, lever...
player-take-damage: false
mobs-spawn: false
weather-cycle: false
food-decrease: false
force-spawn-on-connect: true

# Other
pickaxe-command: /server hub # Don't forget to add '/' before the command
minimum_y_coordinate: 0.0 # Height to which the player will be teleported when falling into the void

# Message
cannot-break-block: "You can not break block here !"
cannot-place-block: "You can not place block here !"
cannot-drop-item: "You can not drop item on the ground !"
heal-is-disabled: "Heal is disabled"
healed-message: "You have been healed food and life !"
permission-denied: "You do not have permission to do that"
lobby-spawn-set: "Lobby spawn point has been saved. Please reboot the server to save changes !"


